# Generated by Django 4.2.1 on 2023-05-29 19:18

import django.core.validators
from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'genre',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_rating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField()),
                ('background', models.ImageField(null=True, upload_to='images/background/')),
                ('banner', models.ImageField(null=True, upload_to='images/banner/')),
                ('source_link', models.FileField(null=True, upload_to='videos/movie/')),
                ('trailer_link', models.FileField(null=True, upload_to='videos/trailer/')),
                ('date_submit', models.DateField(auto_now_add=True)),
                ('date_release', models.DateField(null=True)),
                ('count_view', models.IntegerField(default=0)),
                ('is_showing', models.BooleanField(default=False)),
                ('movie_length', models.CharField(max_length=100, null=True)),
                ('age_recommend', models.IntegerField(null=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'db_table': 'movie',
                'ordering': [models.OrderBy(django.db.models.functions.comparison.Cast('date_release', models.DateTimeField()), descending=True)],
            },
        ),
    ]
