# Generated by Django 4.2.1 on 2023-05-17 08:25

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'genre',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('banner', models.TextField()),
                ('source_link', models.TextField()),
                ('trailer_link', models.TextField()),
                ('date_submit', models.DateField(auto_now_add=True)),
                ('date_release', models.DateField()),
                ('count_view', models.IntegerField(default=0)),
                ('is_showing', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'movie',
                'ordering': [models.OrderBy(django.db.models.functions.comparison.Cast('my_date', models.DateTimeField()), descending=True)],
            },
        ),
    ]
