# Generated by Django 4.2.1 on 2023-05-19 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_genre_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
