//movie
export const GET_NETFLIX_ORIGINALS='GET_NETFLIX_ORIGINALS';

export const GET_TRENDING_MOVIES='GET_TRENDING_MOVIES'
export const GET_TOP_RATED_MOVIES='GET_TOP_RATED_MOVIES'
export const GET_ACTION_MOVIES='GET_ACTION_MOVIES'
export const GET_COMEDY_MOVIES='GET_COMEDY_MOVIES'
export const GET_HORROR_MOVIES='GET_HORROR_MOVIES'
export const GET_ROMANCE_MOVIES='GET_ROMANCE_MOVIES'
export const GET_DOCUMENTARIES_MOVIES='GET_DOCUMENTARIES_MOVIES'
export const  GET_SEARCH_MOVIES='GET_SEARCH_MOVIES'
             
export const SET_MOVIE_DETAIL='SET_MOVIE_DETAIL';
export const SET_MOVIE_CARD='SET_MOVIE_CARD';
export const DELETE_MOVIE_CART='DELETE_MOVIE_CART';
export const GET_RECOMMEND_MOVIES='GET_RECOMMEND_MOVIES';
export const GET_MOVIE_WATCH='GET_MOVIE_WATCH';
export const DELETE_ALL_MOVIE_CART='DELETE_ALL_MOVIE_CART';

//User
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_MY_MOVIES = 'GET_MY_MOVIES';
export const GET_EXPLORE_MOVIE_PAGE = 'GET_EXPLORE_MOVIE_PAGE';

export const RESET_STATE = 'RESET_STATE';
